// Generates a doctor-ready 1-page PDF summarising the user's semen
// analysis results, WHO 2021 classifications, and FM code. Lazy-loads
// jspdf (~300KB) so it doesn't bloat the initial bundle.
//
// Output is designed for the "bring this to your next appointment"
// use case: clean black-on-white layout, no colour, no decorative
// elements — just the data a doctor needs to see at a glance.

let jsPDFPromise = null;

function loadJsPDF() {
  if (!jsPDFPromise) {
    jsPDFPromise = import("jspdf").then((mod) => mod.jsPDF || mod.default?.jsPDF || mod.default);
  }
  return jsPDFPromise;
}

const STATUS_LABEL = {
  NORMAL: "Normal",
  WARNING: "Borderline",
  CRITICAL: "Needs Focus",
};

export async function generateReportPdf({ result, fmCode, verdictLabel, tmsc }) {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = margin;

  // ── Helper: draw text and advance Y ────────────────────────────
  const text = (str, x, opts = {}) => {
    doc.setFontSize(opts.size || 10);
    doc.setFont("helvetica", opts.style || "normal");
    doc.setTextColor(opts.color || "#000000");
    doc.text(str, x, y);
    if (!opts.noAdvance) y += (opts.size || 10) * 0.45;
  };

  const line = () => {
    doc.setDrawColor("#cccccc");
    doc.setLineWidth(0.3);
    doc.line(margin, y, pageW - margin, y);
    y += 4;
  };

  // ── Header ─────────────────────────────────────────────────────
  text("ForMen Digital Clinic", margin, { size: 14, style: "bold" });
  text("Lab Report Explainer — Semen Analysis Summary", margin, { size: 9, color: "#666666" });
  y += 2;
  line();

  // ── Meta row ───────────────────────────────────────────────────
  const date = new Date().toLocaleDateString("en-IN", {
    year: "numeric", month: "long", day: "numeric",
  });
  text(`Date: ${date}`, margin, { size: 9 });
  text(`FM Code: ${fmCode}`, margin + contentW / 2, { size: 9 });
  y += 2;

  // ── Verdict ────────────────────────────────────────────────────
  text("Summary", margin, { size: 12, style: "bold" });
  text(verdictLabel, margin, { size: 11 });
  y += 3;

  // ── TMSC ───────────────────────────────────────────────────────
  if (tmsc) {
    text(`Total Motile Sperm Count: ${tmsc.value < 1 ? "Below 1" : tmsc.value} million — ${tmsc.tierLabel}`, margin, { size: 9, color: "#333333" });
    y += 4;
  }

  // ── Parameters table ───────────────────────────────────────────
  line();

  // Table header
  const cols = [margin, margin + 55, margin + 85, margin + 115, margin + 145];
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor("#666666");
  doc.text("Parameter", cols[0], y);
  doc.text("Value", cols[1], y);
  doc.text("Unit", cols[2], y);
  doc.text("WHO Range", cols[3], y);
  doc.text("Status", cols[4], y);
  y += 5;
  line();

  // Table rows
  const paramOrder = ["spermCount", "motility", "morphology", "volume", "pH", "wbc"];
  const paramLabels = {
    spermCount: "Sperm Count",
    motility: "Total Motility",
    morphology: "Morphology",
    volume: "Volume",
    pH: "pH",
    wbc: "WBC (Pus Cells)",
  };

  doc.setFont("helvetica", "normal");
  doc.setTextColor("#000000");
  doc.setFontSize(9);

  for (const key of paramOrder) {
    const p = result.parameters[key];
    if (!p) continue;

    const statusText = STATUS_LABEL[p.status] || p.status;
    const statusColor = p.status === "NORMAL" ? "#2C6B47" : p.status === "WARNING" ? "#B77900" : "#9A4A2D";

    doc.setTextColor("#000000");
    doc.text(paramLabels[key] || key, cols[0], y);

    const val = Number.isInteger(p.value) ? String(p.value) : p.value.toFixed(1);
    doc.text(val, cols[1], y);
    doc.text(p.unit || "", cols[2], y);
    doc.text(p.whoRange || "", cols[3], y);

    doc.setTextColor(statusColor);
    doc.setFont("helvetica", "bold");
    doc.text(statusText, cols[4], y);
    doc.setFont("helvetica", "normal");

    y += 6;
  }

  y += 4;
  line();

  // ── Disclaimer ─────────────────────────────────────────────────
  y += 2;
  doc.setFontSize(8);
  doc.setTextColor("#999999");
  const disclaimer = [
    "This is a plain-language summary compared to WHO 2021 (6th Edition) reference ranges.",
    "It is NOT a medical diagnosis. For clinical decisions, please consult a qualified doctor.",
    "Borderline/Needs-Focus tiers use clinical convention, not WHO-defined thresholds.",
    "",
    "Generated by ForMen Digital Clinic — Lab Report Explainer",
    "https://formen.health/pages/lab-report-explainer",
  ];
  for (const d of disclaimer) {
    if (d) doc.text(d, margin, y);
    y += 3.5;
  }

  // ── Save ───────────────────────────────────────────────────────
  doc.save(`ForMen-Report-${fmCode}.pdf`);
}
