export const suggestions = [
  {
    category: "Food",
    icon: "🥗",
    items: [
      {
        name: "Zinc-Rich Foods",
        plain: "Zinc is essential for testosterone production and sperm development. Low zinc levels are directly linked to reduced sperm count and quality.",
        examples: "Oysters, pumpkin seeds, lean beef, chickpeas, lentils, cashews.",
        tip: "Aim for 11 mg/day — roughly 85g of beef or a handful of pumpkin seeds covers it.",
      },
      {
        name: "Antioxidant-Rich Fruits & Vegetables",
        plain: "Antioxidants neutralize free radicals that damage sperm DNA and membranes. Colorful produce is your best natural source.",
        examples: "Berries (blueberries, strawberries), tomatoes, spinach, kale, bell peppers, pomegranate.",
        tip: "Aim for 5+ servings of colorful fruits and vegetables daily.",
      },
      {
        name: "Omega-3 Fatty Acids",
        plain: "Omega-3s improve sperm membrane fluidity, which is critical for motility and the ability to penetrate an egg.",
        examples: "Salmon, mackerel, sardines, walnuts, flaxseeds, chia seeds.",
        tip: "2-3 servings of fatty fish per week provides a solid omega-3 foundation.",
      },
      {
        name: "Folate-Rich Foods",
        plain: "Folate supports DNA synthesis during sperm production. Low folate is associated with higher rates of chromosomal abnormalities in sperm.",
        examples: "Dark leafy greens, asparagus, avocado, citrus fruits, beans, fortified cereals.",
        tip: "Pair with vitamin B12 sources for maximum DNA synthesis support.",
      },
      {
        name: "Selenium Sources",
        plain: "Selenium is a key component of proteins that protect sperm from oxidative damage and support healthy sperm formation.",
        examples: "Brazil nuts (1-2 per day is enough), eggs, sunflower seeds, brown rice, mushrooms.",
        tip: "Just 2 Brazil nuts daily can meet your full selenium requirement — don't overdo it.",
      },
      {
        name: "Vitamin D Sources",
        plain: "Vitamin D receptors are found in sperm cells, and deficiency is linked to lower motility and count. Most men in urban India are deficient.",
        examples: "Egg yolks, fortified milk, fatty fish, mushrooms exposed to sunlight.",
        tip: "Morning sunlight (15-20 min) is the most effective source. Supplement if your levels are below 30 ng/mL.",
      },
    ],
  },
  {
    category: "Supplements",
    icon: "💊",
    items: [
      {
        name: "Coenzyme Q10 (CoQ10)",
        plain: "CoQ10 powers the mitochondria in sperm tails — the engine that drives motility. Supplementation has shown improvements in both count and motility in clinical studies.",
        dosage: "200-400 mg/day",
        evidence: "Multiple RCTs show significant improvement in sperm concentration and motility after 3-6 months.",
        source: "Safarinejad MR. Efficacy of coenzyme Q10 on semen parameters. J Urol. 2009;182(1):237-248.",
        sourceId: "PMID: 19447425",
      },
      {
        name: "Zinc",
        plain: "Zinc plays a direct role in testosterone production, sperm maturation, and maintaining sperm membrane integrity.",
        dosage: "25-50 mg/day (elemental zinc)",
        evidence: "Zinc supplementation in deficient men has shown 74% increase in sperm count in some studies.",
        source: "Fallah A, et al. Zinc is an essential element for male fertility. J Reprod Infertil. 2018;19(2):69-81.",
        sourceId: "PMID: 30009140",
      },
      {
        name: "L-Carnitine",
        plain: "L-Carnitine transports fatty acids into sperm mitochondria for energy production, directly fueling sperm movement.",
        dosage: "2-3 g/day (as L-carnitine or acetyl-L-carnitine)",
        evidence: "Well-studied for improving progressive motility, especially in men with asthenozoospermia.",
        source: "Balercia G, et al. Placebo-controlled double-blind randomized trial on L-carnitine. Fertil Steril. 2005;84(3):662-671.",
        sourceId: "PMID: 16169400",
      },
      {
        name: "Vitamin C & Vitamin E",
        plain: "This antioxidant duo works together — Vitamin C protects in water-based environments, Vitamin E in fat-based cell membranes — to shield sperm from oxidative damage.",
        dosage: "Vitamin C: 500-1000 mg/day, Vitamin E: 400 IU/day",
        evidence: "Combined supplementation reduces sperm DNA fragmentation and improves morphology.",
        source: "Greco E, et al. Reduction of the incidence of sperm DNA fragmentation by oral antioxidant treatment. J Androl. 2005;26(3):349-353.",
        sourceId: "PMID: 15867002",
      },
      {
        name: "Ashwagandha (Withania somnifera)",
        plain: "An adaptogen that reduces cortisol and oxidative stress while supporting testosterone levels. Well-studied in the Indian medical system.",
        dosage: "300-600 mg/day (standardized root extract, KSM-66)",
        evidence: "Clinical trials show improvements in sperm count, motility, and testosterone in stressed/infertile men.",
        source: "Ambiye VR, et al. Clinical evaluation of spermatogenic activity of Ashwagandha root extract. Evid Based Complement Alternat Med. 2013;2013:571420.",
        sourceId: "PMID: 24371462",
      },
      {
        name: "Folic Acid + Vitamin B12",
        plain: "Both B-vitamins are essential for DNA synthesis during the 74-day sperm production cycle. Deficiency increases chromosomal errors.",
        dosage: "Folic acid: 400-800 mcg/day, B12: 1000 mcg/day",
        evidence: "Combined supplementation improves sperm count and reduces DNA fragmentation.",
        source: "Wong WY, et al. Effects of folic acid and zinc sulfate on male factor subfertility. Fertil Steril. 2002;77(3):491-498.",
        sourceId: "PMID: 11872201",
      },
    ],
  },
  {
    category: "Tests When Required",
    icon: "🔬",
    items: [
      {
        name: "DNA Fragmentation Index (DFI)",
        plain: "Measures damage to the DNA inside each sperm. Even if sperm look normal and move well, damaged DNA can cause poor embryo development or repeated miscarriage.",
        when: "Recurrent pregnancy loss, failed IVF/ICSI, unexplained infertility despite normal routine results.",
        cost: "₹3,000–₹8,000",
      },
      {
        name: "Hormone Panel (FSH, LH, Testosterone, Prolactin)",
        plain: "Blood tests checking if your brain and testes are communicating properly. Hormonal imbalances can cause low sperm production even when the testes are healthy.",
        when: "Low sperm count, low libido, suspected hormonal disorder.",
        cost: "₹800–₹2,500",
      },
      {
        name: "Scrotal Doppler Ultrasound",
        plain: "Detects varicocele — enlarged veins in the scrotum that raise testicular temperature and damage sperm production. One of the most common and treatable causes of male infertility.",
        when: "Abnormal semen parameters, palpable varicocele, testicular discomfort.",
        cost: "₹1,000–₹3,000",
      },
      {
        name: "Reactive Oxygen Species (ROS) Testing",
        plain: "Measures oxidative stress in semen. Too many free radicals damage sperm membrane and DNA — often caused by smoking, obesity, or environmental toxins.",
        when: "Unexplained infertility, lifestyle risk factors present.",
        cost: "₹2,000–₹5,000",
      },
      {
        name: "Anti-Sperm Antibodies (ASA)",
        plain: "Detects if your immune system is mistakenly attacking your own sperm, impairing their movement and ability to fertilise.",
        when: "Unexplained infertility, testicular injury or infection history, post-vasectomy reversal.",
        cost: "₹1,500–₹4,000",
      },
      {
        name: "Genetic Testing (Karyotype + Y-Microdeletion)",
        plain: "Checks for chromosomal abnormalities or missing sections of the Y chromosome responsible for sperm production.",
        when: "Severe oligospermia or azoospermia, recurrent pregnancy loss, before IVF/ICSI.",
        cost: "₹5,000–₹15,000",
      },
    ],
  },
];
